name: 'With Pybind11 Action'
description: 'Cacheable Pybind11 installation from source for your Github Actions.'
author: 'florianblume'
branding:
  icon: 'scissors'
  color: 'blue'
inputs:
  dir:
    description: 'Directory to clone Pybind11, required to cache path'
    default: 'pybind11-install'
  cached:
    description: "Whether to build Pybind11 completely again or just run make install from previously built binaries."
    default: false
  pybind11-version:
    description: 'Pybind11 version to be installed.'
    required: true
    default: '2.8.0'
  CMAKE_CXX_COMPILER:
    default: g++
    required: false
  CMAKE_INSTALL_PREFIX:
    default: /usr/local
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
