name: "build-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache OpenCV
      id: opencv-cache
      uses: actions/cache@v2
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencv-cache
    - uses: ./
      with:
        dir: ./opencv-install
        opencv-version: '4.0.0'
    - run: |
        cmake -C tests/basic_test
        make -C tests/basic_test